### ISSUE TITLE
Lazy Load vuex-gallery images

### ISSUE THREAD

**Issue by ooade** [ooade/vuex-examples#5]
Some folks uploaded some large images to the gallery which causes the site to be unresponsive till the image loads finish. We could use a library I wrote a while ago to achieve this https://github.com/ooade/pimg

**Comment by krns** [comment]
I'm working on it!

**Comment by krns** [comment]
Just saw you already implemented it in 2ea9dc88a93e2f72a171ace84f4081a7381a833e

**Comment by ooade** [comment]
Oh! Didn't know I had solved it :sweat:
