### ISSUE TITLE
Close branches, Open folders

### ISSUE THREAD

**Issue by ooade** [ooade/vuex-examples#6]
The branches thing might be a little bit costly and a slower approach to move around this project. I suggest we change to a folder view since it's easy to use multiple stores in Vue(x) projects.

Anyone willing to take this?
Folder Structure would be like this:
- starter-files (contains everything in the master branch except src and store, the rest needs to be merged)
- auth (contains everything in the auth branch except src and store)
- and so on...

**Comment by ooade** [comment]
Do you mind working on this @krns?

**Comment by ooade** [comment]
Besides, if you're good with testing Vue Components, I might need some help with it over at the [pimg - superb lazyloader](https://github.com/ooade/pimg/issues/5) repo

**Comment by fgriberi** [comment]
Hi @ooade, I'm available to contribute with this issue, so the idea here is to move the stale branches (auth, counter, simple-todo, shopping-cart and firestore) into folders on master?

**Comment by ooade** [comment]
Yeah @fgriberi  :+1:

**Comment by fgriberi** [comment]
@ooade cool! I'm going to work in this issue

**Comment by ooade** [comment]
Okay @fgriberi. That's good to know :muscle:

**Comment by fgriberi** [comment]
@ooade I've already created a PR for this issue, just take a look

**Comment by ooade** [comment]
Okay. I will

**Comment by fgriberi** [comment]
@ooade Thx... It's possible to assign me the issue and close it?
