### ISSUE TITLE
Fix vulnerabilities, update packages

### ISSUE THREAD

**Issue by ooade** [ooade/vuex-examples#9]
Shout out to @fgriberi. He really helped so far in the revamping of the repository. Thanks a lot, man :muscle: 

If you noticed, I created a staging branch to push some other things which fixes vulnerabilites(npm audix fix --force) in the auth folder. (Pun)It opened up a bridge to our world and caused some aliens to move freely. Many things got broken as it upgraded the webpack version and some other packages which had some breaking changes. I had to upgrade them all and put everything in order.

Anyone interested could fix the vulnerabilities in other folders and push. BTW, you can send a vulnerability fix per PR, no problem.

**Comment by FDiskas** [comment]
I would help with love :)

**Comment by ooade** [comment]
@FDiskas Feel free to dive in :rocket: :rocket:

**Comment by ooade** [comment]
@FDiskas Make sure you work on the **staging branch** though

**Comment by ooade** [comment]
If you have any issues, let me know. Thank you.

**Comment by FDiskas** [comment]
@ooade check this out

**Comment by FDiskas** [comment]
Any news?

**Comment by ooade** [comment]
@FDiskas I'm on it now

**Comment by FDiskas** [comment]
And this was reverted? Did I miss something?
